SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[User_Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LastName] [nchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Password] [nchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[UserName] [nchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[AccesGroup] [int] NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[User_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
