USE [master]
GO

/****** Object:  Database [SCMDatabase]    Script Date: 2/24/2016 10:52:23 AM ******/
CREATE DATABASE [SCMDatabase]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SMCDatabase', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SMCDatabase.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'SMCDatabase_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\SMCDatabase_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [SCMDatabase] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SCMDatabase].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SCMDatabase] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SCMDatabase] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SCMDatabase] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SCMDatabase] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SCMDatabase] SET ARITHABORT OFF 
GO

ALTER DATABASE [SCMDatabase] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SCMDatabase] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SCMDatabase] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SCMDatabase] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SCMDatabase] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SCMDatabase] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SCMDatabase] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SCMDatabase] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SCMDatabase] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SCMDatabase] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SCMDatabase] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SCMDatabase] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SCMDatabase] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SCMDatabase] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SCMDatabase] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SCMDatabase] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SCMDatabase] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SCMDatabase] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [SCMDatabase] SET  MULTI_USER 
GO

ALTER DATABASE [SCMDatabase] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SCMDatabase] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SCMDatabase] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SCMDatabase] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [SCMDatabase] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SCMDatabase] SET  READ_WRITE 
GO


